### ISSUE TITLE
Background color not the same when collapsed

### ISSUE THREAD

**Issue by laraning** [ebess/nova-collapsible-sidebar#1]
Hi ebess,

Nice asset tool for Nova! Thanks for that.

Still, I think I found a small improvement you might think about. So, if you work with another background color like my case:
![image](https://user-images.githubusercontent.com/35408392/46432189-e7ca3c80-c74d-11e8-8f14-68a129f68103.png)

It will then don't keep the same background color when it is collapsed, like this:
![image](https://user-images.githubusercontent.com/35408392/46432215-fb75a300-c74d-11e8-915c-cc31e7ac327a.png)

It would be awesome if it could keep the same background color even when it's collapsed.

Thanks,
Bruno

**Comment by ebess** [comment]
https://github.com/ebess/nova-collapsible-sidebar/releases/tag/0.1.1
