### ISSUE TITLE
[QUESTION] Not working in nova latest version

### ISSUE THREAD

**Issue by stezani** [ebess/nova-collapsible-sidebar#3]
### Prerequisites

* [ ] Able to reproduce the behaviour outside of your code, the problem is isolated to Laravel Excel.
* [ X] Checked that your issue isn't already filed.
* [ X] Checked if no PR was submitted that fixes this problem.

### Versions

* PHP version: 7.1.25
* Laravel version: 5.7
* Nova version: latest
* Package version: latest

### Description

Hi! I've found your plugin via novapackages. I've read the guide for install this plugin but after `nova:publish` command in `resources/views/vendor/nova/` i haven't any file called `layout.blade.php` but i have only the folder `partials`. I've tried to create manually this file and insert the code with `collapsible-sidebar` tag but after that i receive a blank page in my project. 
### Steps to Reproduce

Install a fresh nova project and after install the package via composer.

**Expected behavior:**

Hide/Show laravel nova sidebar

**Actual behavior:** 

Blank screen without any laravel nova graphic

**Comment by Xpedigo** [comment]
@ebess I agree, will be great if it will work on last version of laravel/nova

Thank you!

**Comment by ebess** [comment]
@Xpedigo @stezani 
just tried the laravel/nova:2.0.1 release. worked fine for me.

```bash
php artisan nova:publish
# or only for views
php artisan vendor:publish --tag nova-views --force

....
Copied File [/vendor/laravel/nova/resources/views/layout.blade.php] To [/resources/views/vendor/nova/layout.blade.php]
```

The layout file has been published. If the layout file does not get published, just copy it manually: `vendor/laravel/nova/resources/views/layout.blade.php`. 

Which nova version are you using?

**Comment by ebess** [comment]
PS: I see now, the `layout.blade.php` is not published by the most recent version of nova. So, you need to copy it by hand. I will adjust the readme.
